apiVersion: apps/v1
kind: Deployment
metadata:
  name: warpstream-app-producer
  labels:
    app: warpstream-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warpstream-producer
  template:
    metadata:
      labels:
        app: warpstream-producer
    spec:
      containers:
        - name: warpstream-producer-container
          image: mariovalente/warpstrem-producer:v1
          ports:
            - containerPort: 3001
          env:
            - name: TOPIC_NAME
              value: "warpstream-topic"
            - name: BROKER_URL
              value: "warpstream-agent:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: warpstream-service
spec:
  selector:
    app: warpstream-producer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warpstream-app-consumer
  labels:
    app: warpstream-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warpstream-consumer
  template:
    metadata:
      labels:
        app: warpstream-consumer
    spec:
      containers:
        - name: warpstream-consumer-container
          image: mariovalente/warpstrem-consumer:v1
          ports:
            - containerPort: 3002
          env:
            - name: TOPIC_NAME
              value: "warpstream-topic"
            - name: BROKER_URL
              value: "warpstream-agent:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: warpstream-service
spec:
  selector:
    app: warpstream-consumer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
